add_newline = true

format= """\
[â•­](dimmed white)$username$directory$aws$azure$kubernetes$terraform$python$git_branch$git_state$git_status$direnv$shell$fill($username@$hostname)$fill$cmd_duration$time
[â•°](dimmed white)[ï‘ ](dimmed green)[ï‘ ](green)[ï‘ ](bold green)$character"""


[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = 'bold blue'
symbol = 'ğŸ…°â˜ï¸'


[azure]
disabled = false
format = '[$symbol($username) | ($subscription)]($style) '
symbol = 'ó° … '
style = 'blue bold'

[character]
format = "$symbol"
success_symbol = "[â®](green)"
error_symbol = "[â®](red)"
vicmd_symbol = "[â®Ÿ](bright purple)"
disabled = false

[cmd_duration]
min_time = 500

[directory]
truncation_length = 5
truncate_to_repo = false

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[username]
style_root = "red"
format = "[$user]($style)"
show_always = false

[kubernetes]
symbol = 'â˜¸ '
format = '[$symbol$context( \($namespace\))]($style) '
style = 'green bold'
disabled = false

[kubernetes.context_aliases]
"default" = "home-cluster"

[time]
disabled = false
format = "[$time]($style) ï€—"
style = "green"

[fill]
symbol = " "

[shell]
disabled = false
fish_indicator = "ğŸŸ"
powershell_indicator = "ï‘ _"
bash_indicator = "î•"
